### ISSUE TITLE
Im a little confused

### ISSUE THREAD

**Issue by DarkPheonix2122** [Mangium/mangium#7]
How do i make a server?

**Comment by DarkPheonix2122** [comment]
like how do i create a server for my game, the servers creation is not working, it is greyed out

**Comment by DarkPheonix2122** [comment]
and the dash says 404 not found

**Comment by DarkPheonix2122** [comment]
![Screenshot 2020-10-21 at 9 08 27 AM](https://user-images.githubusercontent.com/66898756/96723814-0e7f5e00-137d-11eb-8467-9a3c0c226b26.png)

**Comment by Floffah** [comment]
sorry this project isn't finished. once it reaches the 0.0.1 milestone it will be working

**Comment by DarkPheonix2122** [comment]
Okay, thx! btw what do i do to become a contributer

**Comment by Floffah** [comment]
create a fork of this project and contribute some code!
doing this right now probably wouldn't be a good idea as i am going to port it to typescript with yarn workspaces but check back soon for that

**Comment by DarkPheonix2122** [comment]
okay
if you want, email me at jcplayz111@gmail.com when i can!

**Comment by Floffah** [comment]
there is also a discord server you can chat in https://discord.gg/SPmvXyp

**Comment by DarkPheonix2122** [comment]
k, i will join when i can!
